### PR TITLE
Ensure catalog suites are always ordered

### LINKED ISSUE #583: catalog generator no longer keeps the suites in order
this is probably broken by #561

### PR DESCRIPTION
**Pull request by javierpena**
Previously, we were not ensuring an order when getting the list of
suites in outputTestCases(). This caused issues, because the CATALOG.md
file could be changed by any PR, breaking order.

Fixes #583

### CODE REVIEW

**Review by jun-rh — APPROVED** [review]

File: cmd/tnf/generate/catalog/catalog.go [hunk 1]
```diff
@@ -201,6 +201,9 @@ func outputTestCases() {
 	// we need the list of suite's names
 	suites := getSuitesFromIdentifiers(keys)
 
+	// Sort the list of suite names
+	sort.Strings(suites)
```
Comment (edcdavid) [inline cmd/tnf/generate/catalog/catalog.go:205]: Shoudn't we also checkin the sorted catalog.md?

**Review by edcdavid — APPROVED** [review]

File: cmd/tnf/generate/catalog/catalog.go (hunk 1 above)
Comment (jun-rh) [reply cmd/tnf/generate/catalog/catalog.go:205]: it's sorted right now. we've been careful about messing it up since the bug was introduced :smile:
